### ISSUE TITLE
Cannot Initialize device

### ISSUE THREAD

**Issue by patlas** [recallfx/sun-logger#1]
Hi,
I cannot connect to my sun2000 with your code, I have connect USB-UART (ft232) and max485 and attach it to sun2000 A1/B1 pins (1st and 3rd pin on connector). Do I have to do something else to perform communication (enable some option via mobile app or whatever)?

If it's possible please mail me at patlas92 (at) wp.pl

Thanks in advace
Patryk

**Comment by recallfx** [comment]
Sorry buddy, that code should help you started, but it is not a final solution.
